name: Docker Image For Dependencies

on:
  workflow_dispatch
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker with Dependencies
      run: docker build . --file Dockerfile --tag regctsem:dependencies
      
    - name: Login to GitHub Packages
      run: echo ${{secrets.GH_LOGIN}} | docker login ghcr.io -u jhorzek --password-stdin
      
    - name: Push Package
      run: docker push ghcr.io/jhorzek/regctsem:dependencies
